theme: jekyll-theme-minimal
title: Scavenger hunt 2021
description: You've made it this far, can you make it a little further?
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
github:
  is_project_page: false
