theme: jekyll-theme-minimal
title: Netlight Oslo scavenger hunt 2021
description: Having technical issues, or otherwise stuck? Ping @Martin.O on Slack!
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
github:
  is\_project\_page: false
