theme: jekyll-theme-minimal
title: Post 7
description: Munchmuseet
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
github:
  is_project_page: false
